export const postsData = [   
    {   
        profileName: `Mindset Machine`,
        handle: `@Mindset_Machine`,
        profileLink: `https://x.com/Mindset_Machine`,
        profilePic: `images/Mindset-Machine.jpg`,
        likes: 802,
        reposts: 155,
        postText: `Be the man who can survive the darkest phase of his life then restart, reform, refocus, and rebuild himself again.`,
        bookmarks: ``,
        replies: [],
        isLiked: false,
        isPosted: false,
        isBookmarked: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
    },    
    {   
        profileName: `Fabrizio Romano`,
        handle: `@FabrizioRomano`,
        profileLink: `https://x.com/FabrizioRomano`,
        profilePic: `images/Fabrizio-Romano.jpg`,
        likes: 51000,
        reposts: 5100,
        postText: `🚨🌍 African Player of the Year Finalists have been announced by CAF tonight 👀✨ Who would you vote as winner? 🏅`,
        bookmarks: ``,
        replies: [
                  {
                    profileName: `Liverpool FC`,
                    handle: `@LFC`,
                    profileLink: `https://x.com/LFC`,
                    profilePic: `images/liverpool.jpg`,
                    postText: `Where is Mo Salah???😢`,
            },
                  {
                    profileName: `Atalanta B.C.`,
                    handle: `@Atalanta_BC`,
                    profileLink: `https://x.com/Atalanta_BC`,
                    profilePic: `images/Atalanta.jpg`,
                    postText: `Ademola Lookman for the win 🏆`,
            },
                  {
                    profileName: `Troll Football`,
                    handle: `@TrollFootball`,
                    profileLink: `https://x.com/TrollFootball`,
                    profilePic: `images/Trollfootball.jpg`,
                    postText: `Not my idolo, Penaldo!`,
            },
        ],
        isLiked: false,
        isPosted: false,
        isBookMarked: false,
        uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs2',
    },
        {
        profileName: `Alexander`,
        handle: `@aawukug`,
        profileLink: `https://x.com/aawukug`,
        profilePic: `images/aawukug.jpg`,
        likes: 10,
        reposts: 3,
        postText: `Can I get a job at Snapchat Inc with learning only HTML?`,
        bookmarks: ``,
        replies: [
            {
                profileName: `richie.online`,
                handle: `@RichardAidoo_O`,
                profileLink: `https://x.com/RichardAidoo_O`,
                profilePic: `images/Richie.jpg`,
                postText: `Bro, go get a job at KFC.`,
            },
            {
                profileName: `נתנאל`,
                handle: `@_nattyyyyyy`,
                profileLink: `https://x.com/_nattyyyyyy`,
                profilePic: `images/Nat.jpg`,
                postText: `You have a long way, but keep going. ❤️`,
            },
        ],
        isLiked: false,
        isPosted: false,
        isBookMarked: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys45',
    },  
    {
        profileName: `J`,
        handle: `@jwaweruh`,
        profileLink: `https://x.com/jwaweruh`,
        profilePic: `images/J.jpg`,
        likes: 157,
        reposts: 78,
        postText: `We need Ten Hag and his family jailed for what he did to Amad.`,
        bookmarks: ``,
        replies: [
            {
                profileName: `Uncle Wilson.`,
                handle: `@iam_wilsons`,
                profileLink: `https://x.com/iam_wilsons`,
                profilePic: `images/wilson.jpg`,
                postText: `Hand go soon touch that werey.`,
            },
            {
                profileName: `Emmy`,
                handle: `@Emmyking99`,
                profileLink: `https://x.com/Emmyking99`,
                profilePic: `images/Emmy.jpg`,
                postText: `He needs to be on FBI most wanted list.`,
            },
        ],
        isLiked: false,
        isPosted: false,
        isBookMarked: false,
        uuid: `1223c244-22e1-4ee9-8fcd-18845ec06f69`,
    }   
]
